language: go
go:
  - 1.4.1
before_install:
  - go get github.com/mattn/gom
before_script:
  - psql -c 'create database shorty_test;' -U postgres
env:
  - "DBUSER=postgres"
script:
  - $HOME/gopath/bin/gom -test install
  - $HOME/gopath/bin/gom test src/*
addons:
  postgresql: 9.3
